[2024-06-27T02:55:17.319+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T02:55:17.336+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_transfer_to_gcs.upload_to_gcs manual__2024-06-27T02:50:12.818675+00:00 [queued]>
[2024-06-27T02:55:17.344+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_transfer_to_gcs.upload_to_gcs manual__2024-06-27T02:50:12.818675+00:00 [queued]>
[2024-06-27T02:55:17.344+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T02:55:17.352+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_to_gcs> on 2024-06-27 02:50:12.818675+00:00
[2024-06-27T02:55:17.360+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_transfer_to_gcs', 'upload_to_gcs', 'manual__2024-06-27T02:50:12.818675+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/to_gcs.py', '--cfg-path', '/tmp/tmpdprqzse1']
[2024-06-27T02:55:17.361+0000] {standard_task_runner.py:91} INFO - Job 100: Subtask upload_to_gcs
[2024-06-27T02:55:17.365+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=403) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-27T02:55:17.365+0000] {standard_task_runner.py:63} INFO - Started process 407 to run task
[2024-06-27T02:55:17.403+0000] {task_command.py:426} INFO - Running <TaskInstance: data_transfer_to_gcs.upload_to_gcs manual__2024-06-27T02:50:12.818675+00:00 [running]> on host 4d14308606fb
[2024-06-27T02:55:17.495+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_transfer_to_gcs' AIRFLOW_CTX_TASK_ID='upload_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T02:50:12.818675+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-27T02:50:12.818675+00:00'
[2024-06-27T02:55:17.496+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T02:55:17.519+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-27T02:55:17.525+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-27T02:55:17.526+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T02:55:17.527+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 111, in execute
    hook.upload(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 528, in upload
    client = self.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 332, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 308, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 371, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 245, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 295, in _get_credentials_using_key_path
    credentials = google.oauth2.service_account.Credentials.from_service_account_file(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/oauth2/service_account.py", line 258, in from_service_account_file
    info, signer = _service_account_info.from_filename(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/credentials/gcs_service_account.json'
[2024-06-27T02:55:17.538+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_transfer_to_gcs, task_id=upload_to_gcs, run_id=manual__2024-06-27T02:50:12.818675+00:00, execution_date=20240627T025012, start_date=20240627T025517, end_date=20240627T025517
[2024-06-27T02:55:17.547+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 100 for task upload_to_gcs ([Errno 2] No such file or directory: '/opt/airflow/dags/credentials/gcs_service_account.json'; 407)
[2024-06-27T02:55:17.579+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-27T02:55:17.607+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T02:55:17.609+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
