[2024-06-26T23:33:42.360+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T23:33:42.385+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_backup_to_gcs.load_data_to_mysql manual__2024-06-26T23:28:39.622719+00:00 [queued]>
[2024-06-26T23:33:42.393+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_backup_to_gcs.load_data_to_mysql manual__2024-06-26T23:28:39.622719+00:00 [queued]>
[2024-06-26T23:33:42.394+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-26T23:33:42.405+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_mysql> on 2024-06-26 23:28:39.622719+00:00
[2024-06-26T23:33:42.414+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_backup_to_gcs', 'load_data_to_mysql', 'manual__2024-06-26T23:28:39.622719+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/to_gcs.py', '--cfg-path', '/tmp/tmpz3oo71dy']
[2024-06-26T23:33:42.415+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask load_data_to_mysql
[2024-06-26T23:33:42.417+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=942) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-26T23:33:42.418+0000] {standard_task_runner.py:63} INFO - Started process 944 to run task
[2024-06-26T23:33:42.445+0000] {task_command.py:426} INFO - Running <TaskInstance: data_backup_to_gcs.load_data_to_mysql manual__2024-06-26T23:28:39.622719+00:00 [running]> on host 1156a65a130e
[2024-06-26T23:33:42.500+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_backup_to_gcs' AIRFLOW_CTX_TASK_ID='load_data_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T23:28:39.622719+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T23:28:39.622719+00:00'
[2024-06-26T23:33:42.500+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T23:33:42.518+0000] {base.py:84} INFO - Using connection ID 'mysql_conn' for task execution.
[2024-06-26T23:33:42.566+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-26T23:33:42.567+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T23:33:42.575+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_backup_to_gcs, task_id=load_data_to_mysql, run_id=manual__2024-06-26T23:28:39.622719+00:00, execution_date=20240626T232839, start_date=20240626T233342, end_date=20240626T233342
[2024-06-26T23:33:42.631+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-26T23:33:42.663+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-26T23:33:42.664+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
