[2024-07-02T00:00:00.846+0000] {processor.py:161} INFO - Started process (PID=2201) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:00:00.846+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:00:00.848+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:00:00.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:00:00.852+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:00:00.851+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:00:00.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:00:00.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.039 seconds
[2024-07-02T00:00:31.455+0000] {processor.py:161} INFO - Started process (PID=2218) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:00:31.457+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:00:31.459+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:00:31.459+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:00:31.464+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:00:31.463+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:00:31.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:00:31.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.039 seconds
[2024-07-02T00:01:01.988+0000] {processor.py:161} INFO - Started process (PID=2235) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:01:01.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:01:01.992+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:01:01.991+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:01:01.995+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:01:01.994+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:01:01.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:01:02.010+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.030 seconds
[2024-07-02T00:01:32.519+0000] {processor.py:161} INFO - Started process (PID=2252) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:01:32.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:01:32.521+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:01:32.520+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:01:32.523+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:01:32.522+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:01:32.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:01:32.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.021 seconds
[2024-07-02T00:02:03.054+0000] {processor.py:161} INFO - Started process (PID=2269) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:02:03.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:02:03.059+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:02:03.059+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:02:03.063+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:02:03.062+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:02:03.064+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:02:03.091+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.044 seconds
[2024-07-02T00:02:33.587+0000] {processor.py:161} INFO - Started process (PID=2286) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:02:33.589+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:02:33.591+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:02:33.590+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:02:33.594+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:02:33.593+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:02:33.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:02:33.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.029 seconds
[2024-07-02T00:03:04.146+0000] {processor.py:161} INFO - Started process (PID=2303) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:03:04.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:03:04.150+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:03:04.150+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:03:04.155+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:03:04.154+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:03:04.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:03:04.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.039 seconds
[2024-07-02T00:03:34.678+0000] {processor.py:161} INFO - Started process (PID=2320) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:03:34.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:03:34.683+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:03:34.683+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:03:34.689+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:03:34.687+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:03:34.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:03:34.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.039 seconds
[2024-07-02T00:04:05.199+0000] {processor.py:161} INFO - Started process (PID=2337) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:04:05.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:04:05.203+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:04:05.202+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:04:05.206+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:04:05.205+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:04:05.207+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:04:05.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.031 seconds
[2024-07-02T00:04:35.706+0000] {processor.py:161} INFO - Started process (PID=2354) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:04:35.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:04:35.709+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:04:35.708+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:04:35.712+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:04:35.712+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:04:35.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:04:35.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.030 seconds
[2024-07-02T00:05:06.271+0000] {processor.py:161} INFO - Started process (PID=2371) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:05:06.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:05:06.275+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:05:06.274+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:05:06.279+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:05:06.278+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:05:06.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:05:06.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.028 seconds
[2024-07-02T00:05:36.807+0000] {processor.py:161} INFO - Started process (PID=2388) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:05:36.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:05:36.812+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:05:36.812+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:05:36.818+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:05:36.816+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:05:36.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:05:36.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.037 seconds
[2024-07-02T00:06:07.379+0000] {processor.py:161} INFO - Started process (PID=2405) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:06:07.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:06:07.384+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:06:07.383+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:06:07.388+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:06:07.387+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:06:07.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:06:07.411+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.037 seconds
[2024-07-02T00:06:37.917+0000] {processor.py:161} INFO - Started process (PID=2422) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:06:37.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:06:37.920+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:06:37.920+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:06:37.923+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:06:37.922+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:06:37.923+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:06:37.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.028 seconds
[2024-07-02T00:07:08.480+0000] {processor.py:161} INFO - Started process (PID=2439) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:07:08.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:07:08.485+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:07:08.485+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:07:08.490+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:07:08.489+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:07:08.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:07:08.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.041 seconds
[2024-07-02T00:07:39.003+0000] {processor.py:161} INFO - Started process (PID=2456) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:07:39.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:07:39.008+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:07:39.007+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:07:39.012+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:07:39.011+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:07:39.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:07:39.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.038 seconds
[2024-07-02T00:08:09.523+0000] {processor.py:161} INFO - Started process (PID=2473) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:08:09.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:08:09.527+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:08:09.527+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:08:09.532+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:08:09.531+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:08:09.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:08:09.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.038 seconds
[2024-07-02T00:08:40.035+0000] {processor.py:161} INFO - Started process (PID=2490) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:08:40.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:08:40.039+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:08:40.039+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:08:40.043+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:08:40.042+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:08:40.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:08:40.060+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.032 seconds
[2024-07-02T00:09:10.555+0000] {processor.py:161} INFO - Started process (PID=2507) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:09:10.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:09:10.557+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:09:10.557+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:09:10.562+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:09:10.561+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:09:10.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:09:10.585+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.037 seconds
[2024-07-02T00:09:41.070+0000] {processor.py:161} INFO - Started process (PID=2524) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:09:41.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:09:41.074+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:09:41.074+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:09:41.076+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:09:41.076+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:09:41.077+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:09:41.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.028 seconds
[2024-07-02T00:10:11.607+0000] {processor.py:161} INFO - Started process (PID=2541) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:10:11.608+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:10:11.610+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:10:11.609+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:10:11.613+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:10:11.613+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:10:11.614+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:10:11.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.035 seconds
[2024-07-02T00:10:42.139+0000] {processor.py:161} INFO - Started process (PID=2558) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:10:42.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:10:42.144+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:10:42.143+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:10:42.149+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:10:42.147+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:10:42.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:10:42.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.039 seconds
[2024-07-02T00:11:12.718+0000] {processor.py:161} INFO - Started process (PID=2575) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:11:12.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:11:12.722+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:11:12.721+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:11:12.725+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:11:12.724+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:11:12.725+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:11:12.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.027 seconds
[2024-07-02T00:11:43.244+0000] {processor.py:161} INFO - Started process (PID=2592) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:11:43.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:11:43.248+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:11:43.248+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:11:43.254+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:11:43.252+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:11:43.255+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:11:43.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.042 seconds
[2024-07-02T00:12:13.801+0000] {processor.py:161} INFO - Started process (PID=2609) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:12:13.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:12:13.806+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:12:13.805+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:12:13.810+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:12:13.809+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:12:13.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:12:13.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.041 seconds
[2024-07-02T00:12:44.318+0000] {processor.py:161} INFO - Started process (PID=2626) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:12:44.321+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:12:44.322+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:12:44.322+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:12:44.325+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:12:44.325+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:12:44.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:12:44.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.034 seconds
[2024-07-02T00:13:14.853+0000] {processor.py:161} INFO - Started process (PID=2643) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:13:14.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:13:14.857+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:13:14.857+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:13:14.862+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:13:14.861+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:13:14.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:13:14.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.041 seconds
[2024-07-02T00:13:45.374+0000] {processor.py:161} INFO - Started process (PID=2660) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:13:45.377+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:13:45.379+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:13:45.378+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:13:45.384+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:13:45.383+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:13:45.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:13:45.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.041 seconds
[2024-07-02T00:14:15.912+0000] {processor.py:161} INFO - Started process (PID=2677) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:14:15.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:14:15.917+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:14:15.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:14:15.922+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:14:15.921+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:14:15.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:14:15.944+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.036 seconds
[2024-07-02T00:14:46.419+0000] {processor.py:161} INFO - Started process (PID=2694) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:14:46.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:14:46.424+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:14:46.423+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:14:46.429+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:14:46.428+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:14:46.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:14:46.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.034 seconds
[2024-07-02T00:15:16.939+0000] {processor.py:161} INFO - Started process (PID=2711) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:15:16.941+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:15:16.943+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:15:16.943+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:15:16.948+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:15:16.946+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:15:16.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:15:16.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.036 seconds
[2024-07-02T00:15:47.442+0000] {processor.py:161} INFO - Started process (PID=2728) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:15:47.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:15:47.444+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:15:47.444+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:15:47.446+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:15:47.446+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:15:47.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:15:47.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.028 seconds
[2024-07-02T00:16:17.966+0000] {processor.py:161} INFO - Started process (PID=2745) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:16:17.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:16:17.972+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:16:17.971+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:16:17.977+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:16:17.975+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:16:17.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:16:18.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.054 seconds
[2024-07-02T00:16:48.568+0000] {processor.py:161} INFO - Started process (PID=2762) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:16:48.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:16:48.573+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:16:48.573+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:16:48.578+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:16:48.577+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:16:48.579+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:16:48.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.042 seconds
[2024-07-02T00:17:19.130+0000] {processor.py:161} INFO - Started process (PID=2779) to work on /opt/airflow/dags/lineage.py
[2024-07-02T00:17:19.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/lineage.py for tasks to queue
[2024-07-02T00:17:19.133+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:17:19.133+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/lineage.py
[2024-07-02T00:17:19.137+0000] {logging_mixin.py:188} INFO - [2024-07-02T00:17:19.136+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/lineage.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lineage.py", line 4, in <module>
    from datahub_provider.entities import Dataset
ModuleNotFoundError: No module named 'datahub_provider'
[2024-07-02T00:17:19.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/lineage.py
[2024-07-02T00:17:19.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/lineage.py took 0.036 seconds
