[2024-06-26T14:56:27.400+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T14:56:27.421+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_transfer_to_mysql.load_data_to_mysql scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T14:56:27.430+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_transfer_to_mysql.load_data_to_mysql scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-26T14:56:27.430+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-26T14:56:27.443+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_mysql> on 2024-06-25 00:00:00+00:00
[2024-06-26T14:56:27.451+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_transfer_to_mysql', 'load_data_to_mysql', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/data_transfer_dag.py', '--cfg-path', '/tmp/tmpk5zfkwqv']
[2024-06-26T14:56:27.453+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask load_data_to_mysql
[2024-06-26T14:56:27.458+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=207) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-26T14:56:27.458+0000] {standard_task_runner.py:63} INFO - Started process 212 to run task
[2024-06-26T14:56:27.495+0000] {task_command.py:426} INFO - Running <TaskInstance: data_transfer_to_mysql.load_data_to_mysql scheduled__2024-06-25T00:00:00+00:00 [running]> on host 3daaf49f25b2
[2024-06-26T14:56:27.550+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_transfer_to_mysql' AIRFLOW_CTX_TASK_ID='load_data_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-26T14:56:27.550+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T14:56:27.576+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T14:56:27.577+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_transfer_dag.py", line 10, in load_data_to_mysql
    engine = sqlalchemy.create_engine('mysql+pymysql://root:password@localhost:3306/dataset_db')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 80, in dbapi
    return __import__("pymysql")
           ^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pymysql'
[2024-06-26T14:56:27.585+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_transfer_to_mysql, task_id=load_data_to_mysql, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240626T145627, end_date=20240626T145627
[2024-06-26T14:56:27.596+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task load_data_to_mysql (No module named 'pymysql'; 212)
[2024-06-26T14:56:27.632+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T14:56:27.646+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T14:56:27.647+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
